docs: incorrectly encoded url in example
adobe/helix-pages pull request #814
Opened 2021-03-23 13:42 UTC by stefan-guggisberg

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-03-23 13:54 UTC, kptdobe commented
Are you sure about that ? Usually, xml does not like the `&` character...

2021-03-23 14:23 UTC, stefan-guggisberg commented
> Are you sure about that ? Usually, xml does not like the & character...

No, I am not sure. But I think that Fastly doesn't care whether it's xml or not when it is processing the `<esi include` statement. I have a hunch that Fastly doesn't decode the `&amp;` when processing the ESI.

2021-03-23 15:08 UTC, trieloff commented
The feeds in `theblog` seem to work (at least the breakage seems unrelated to the ampersands), but it would be worth testing there to make sure both encoding variants work just as well. I remember some iterations until I found a working set of encodings.

2021-03-24 00:59 UTC, tripodsan requested changes

2021-03-24 00:59 UTC, tripodsan commented on docs/feed.md
> +  <esi:include src="/cgi-bin/feed.xml?src=/en/query-index.json%3Flimit%3D10&id=path&title=title&updated=date">
I don't think this change necessary. the `&amp;` is the correct escaping to use in attributes.

2021-03-24 14:33 UTC, stefan-guggisberg commented
> The feeds in theblog seem to work (at least the breakage seems unrelated to the ampersands), but it would be worth testing there to make sure both encoding variants work just as well.

I have tested both encodings and both work. Closing this PR.

2021-03-24 14:33 UTC, closed without merging